### ISSUE TITLE
Custom Buttons only works on the last one

### ISSUE THREAD

**Issue by jaydee9296** [martec/Rin-Editor#1]
Hello sir, I'm experiencing on bug on adding custom buttons... I have 3 custom buttons added to the editor which are hide, spoiler and spotify. When I try to click one custom button, it shows only the bb code of the last custom button inserted.

![vpnpinas15](https://cloud.githubusercontent.com/assets/8472952/13378729/24d30462-de4a-11e5-87a2-531193dc7f1b.PNG)

I hope this will be fixed soon. I am using Google Chrome browser.

**Comment by martec** [comment]
Fixed in 0.6.1. Thanks for report bug!
