### ISSUE TITLE
Quick reply - remove new line automatically

### ISSUE THREAD

**Issue by Cu8eeeR** [martec/Rin-Editor#14]
Here is the detailed screenshot:
![rin_bug](https://cloud.githubusercontent.com/assets/778890/22702015/9a0730f8-ed5f-11e6-8bd9-e39389f75be7.png)

disccusion here: 
https://community.mybb.com/thread-189422-post-1262064.html#pid1262064

**Comment by martec** [comment]
so different thing that i  understood before.
this is default behaviour of mybb. so unfortunately i will not made change in this.

**Comment by Cu8eeeR** [comment]
I didnt know that :( anyway thank you!
