### ISSUE TITLE
Compatibility with XThreads?

### ISSUE THREAD

**Issue by Cu8eeeR** [martec/Rin-Editor#15]
When I activate Xthreads plugin from Zinga Burga (http://mybbhacks.zingaburga.com/forumdisplay.php?fid=31) I get this error in console (after deactivation no issue)
![bug2](https://cloud.githubusercontent.com/assets/778890/23671704/7894d36c-036c-11e7-9aa4-4ed4f1ed0175.png)

Before I do anything I would like to ask you if you use this plugin or do you know if it is compatible. 

EDIT: Only Quick quote is not working and in quick reply/edit I see all buttons in editor (even the disabled ones), but everything else works fine. Thank you in advance

**Comment by martec** [comment]
sorry, but i don't know if compatible.

**Comment by Cu8eeeR** [comment]
Is there any way how to solve this issue? I can share my url, user account with admin permissions. I tried it on the fresh install and same issue (only Rin editor and XThreads were installed). XThreads uses 2 JS files loaded for its functionality, it must be cassed by this. Thank you in advance

**Comment by martec** [comment]
i will try here fix incomaptible issue. but not have ETA for now.

**Comment by Cu8eeeR** [comment]
@martec - that would be really great! I am looking forward, feel free to contact me here or on MyBB community board . I can help you with testing.

**Comment by Cu8eeeR** [comment]
Issue fixed (latest version of XThreads is required)
