### ISSUE TITLE
not working well on android

### ISSUE THREAD

**Issue by arturek1666** [martec/Rin-Editor#17]
I try to send an private message using my android phone, i simply did replay write a message and send it but when someone receive the message is complicity blank

**Comment by ErikThiart** [comment]
Is that an editor issue? To me, that sounds more like your PHP is not submitting the content,

**Comment by martec** [comment]
@Eldenroot

Hi,

in default theme? Or some mobile theme?
If using mobile theme (or responsive theme) what name of theme that you using.

**Comment by Eldenroot** [comment]
MyBB 1.8.12 default theme. I dont use any mobile or responsive theme.

I disable put editor in source mode for mobile users in acp and the issue
is fixed.
