### ISSUE TITLE
Quick Edit: Error On Multiple Clicks To Quick Edit Link

### ISSUE THREAD

**Issue by WildcardSearch** [martec/Rin-Editor#19]
When using Rin Editor on a stock copy of MyBB 1.8.12, clicking the quick edit button on any post presents to user with a Rin Editor, but if the user clicks on the link a second time, the following exception occurs:

> uncaught exception: The editor instance "quickedit_554" is already attached to the provided element.

**Comment by martec** [comment]
Hi,

Thanks for report bug!.
For now, open rinbutquick global template and add `	if(CKEDITOR.instances['quickedit_'+pid]) {
		return;
	}` after `var pid = ed_id.replace( /[^0-9]/g, '');`

**Comment by WildcardSearch** [comment]
Thanks for the quick reply. I will apply the patch when I get home (in about ten hours) and report back.

Thanks again 👍

**Comment by WildcardSearch** [comment]
That fixes the issue for me. Thanks 😄

**Comment by WildcardSearch** [comment]
On further testing that created another bug wherein Rin editor didn't work the second time a post was legitimately edited. For the record, this worked for me:

```javascript
	if (typeof CKEDITOR.instances['quickedit_'+pid] !== "undefined" ) {
		CKEDITOR.instances['quickedit_'+pid].destroy();
	}
```

Note there is no return, so the quick edit textarea still gets converted.

**Comment by martec** [comment]
Hi,

thanks for fix. 👍 
I will merge your fix in next version.

**Comment by WildcardSearch** [comment]
> thanks for fix. 👍

You're welcome.

> I will merge your fix in next version.
Great 👍

**Comment by Eldenroot** [comment]
@martec - do you plan to release a new bug fixed version?

**Comment by martec** [comment]
will merge in new version. closed
