### ISSUE TITLE
Issue on mobile devices

### ISSUE THREAD

**Issue by Eldenroot** [martec/Rin-Editor#20]
https://community.mybb.com/thread-189422-post-1287260.html#pid1287260

and 

https://community.mybb.com/thread-189422-post-1287287.html#pid1287287

I am not the only one :(

**Comment by WildcardSearch** [comment]
This is a duplicate of #17 (although this issue is title more appropriately)

**Comment by martec** [comment]
duplicated and closed.

**Comment by martec** [comment]
i cant't reproduce this issue using chrome of android 9 in my test forum https://community.mybb.com/thread-189422-post-1321521.html#pid1321521 . i tried in source and wysiwyg mode.
Closed for now. Create another issue if issue persist.
