### ISSUE TITLE
Console error 

### ISSUE THREAD

**Issue by Eldenroot** [martec/Rin-Editor#21]
I get this error in my browser console (thread view).

![image](https://user-images.githubusercontent.com/778890/32144014-baee5d5a-bcb2-11e7-927c-414018da1ea7.png)

**Comment by Eldenroot** [comment]
@martec

**Comment by Eldenroot** [comment]
Really annoying, this issue is displayed after you quick edit the post or select something for quick quote

**Comment by martec** [comment]
i can't reproduce in FF.

you can provide more detail?
