### ISSUE TITLE
<i></i> not shown in code block (only shown in source mode)

### ISSUE THREAD

**Issue by Eldenroot** [martec/Rin-Editor#22]

**Comment by martec** [comment]
??
for me appear normally in test site using FF.

**Comment by Eldenroot** [comment]
Can you provide me URL of your test site? for me <i> are not displayed...

**Comment by martec** [comment]
for me ok https://i.imgur.com/HRNVQGM.png

for now sorry i need buy one new domain to create new test forum.

**Comment by martec** [comment]
test forum here https://community.mybb.com/thread-189422-post-1321521.html#pid1321521
