### ISSUE TITLE
Img is broken after editing the post

### ISSUE THREAD

**Issue by Eldenroot** [martec/Rin-Editor#23]
Add an imga into the post via image icon (remote URL). After that go and edit your post and go to the source mode and back... save and check you post. Image is broken; .jpg extension is removed somehow automatically

**Comment by martec** [comment]
Hi,

sorry but i can't reproduce issue...
you can give more detail?

**Comment by Eldenroot** [comment]
Do you have your test board? 

I will try to explain better:
1) Post a new reply with image (remote image added via url - image icon). For example this one: https://www.bgextras.co.uk/itemimages/5500360/Carcassonne-Winter-Edition-Mini-Gingerbread-Man-in-German_T_1_D_12019_I_2302_G_0_V_2.jpg - notice: be in a normal mode "not in source mode". -> image will be displayed correctly

`[img]https://www.bgextras.co.uk/itemimages/5500360/Carcassonne-Winter-Edition-Mini-Gingerbread-Man-in-German_T_1_D_12019_I_2302_G_0_V_2.jpg[/img]`

2) After that, go and quick edit your post -> switch to the source mode and save the post
3) refresh the page -> image is not displayed, .jpg is removed from the url. The url was changed to this:

`https://www.bgextras.co.uk/itemimages/5500360/Carcassonne-Winter-Edition-Mini-Gingerbread-Man-in-German_T_1_D_12019_I_2302_G_0_V_2` - .jpg is missing

**Comment by martec** [comment]
for now i only can test in production forum (my test forum domain expired), that only accept images from imgur.
this issue happen too with imgur domain image?

**Comment by Eldenroot** [comment]
Nope, imgur works fine

**Comment by Eldenroot** [comment]
Cannot reproduce again 👍
