### ISSUE TITLE
no text show on mobile

### ISSUE THREAD

**Issue by FrostTorrents** [martec/Rin-Editor#25]
editing/replying/creating threads on mobile device show no text and reply as no text,
works fine on desktop but not any other devices.
https://i.imgur.com/hntiC0K.jpg

**Comment by martec** [comment]
i cant't reproduce this issue using chrome of android 9 in my test forum https://community.mybb.com/thread-189422-post-1321521.html#pid1321521 . i tried in source and wysiwyg mode.
Closed for now. Create another issue if issue persist.
