### ISSUE TITLE
Missing language string for "Image is uploading" in imgur

### ISSUE THREAD

**Issue by Eldenroot** [martec/Rin-Editor#30]
When you adding an image via an Imgur button, the notification is displayed but it is not possible to translate it to my own language. It is in English and I havent found a lang string.

**Comment by martec** [comment]
for now you can edit https://github.com/martec/Rin-Editor/blob/master/jscripts/rin/editor/lang/en.js
and change "images are uploading" string.

**Comment by Eldenroot** [comment]
Thank you!

**Comment by martec** [comment]
moved to language faile of plugin.
