### ISSUE TITLE
How to hide BIDIltr/rtl buttons from editor

### ISSUE THREAD

**Issue by Eldenroot** [martec/Rin-Editor#31]
How to remove BIDI right to left and left to right buttons from editor (v0.9.0). There is no hint in ACP setting and I havent found a working solution :(

Thank you!

**Comment by martec** [comment]
Hi,

to remove add BidiLtr,BidiRtl in Remove buttons from full mode place  and Remove buttons from other place  in ACP.

**Comment by martec** [comment]
reopened so as not to forget to add the comment in the language file.

**Comment by Eldenroot** [comment]
Thank you @martec

**Comment by martec** [comment]
done.
