### ISSUE TITLE
Add image - after hiding image properties setting it looks weird

### ISSUE THREAD

**Issue by Eldenroot** [martec/Rin-Editor#32]
![image](https://user-images.githubusercontent.com/778890/50686482-ea268600-101d-11e9-81b9-fd1957fa553c.png)

Maybe it would need a little bit love (CSS part) after removing the image properties setting. It looks quite weird.

**Comment by martec** [comment]
done.

**Comment by M1suzu** [comment]
Very sorry for reopening this issue but can you please re-add the image properties setting to this plugin again.
The width and height was very helpful options but now when we add big image it fuck up the whole thread without them.

**Comment by martec** [comment]
@M1suzu 

sorry, but no plan to return with image properties setting.
