### ISSUE TITLE
Don't work correct in editpost

### ISSUE THREAD

**Issue by userMacieG** [martec/Rin-Editor#33]
Hi :) 
I have some problem with editor in `editpost`.
After editing a post they stay the same as before.
I use default mybb style code in template and I dont edit plugin files.

**Comment by userMacieG** [comment]
I solve problem by removing thread and creating again but why only in on this one specified thread problem start exists?

**Comment by martec** [comment]
i need steps to reproduce the issue.

**Comment by martec** [comment]
closed because no reply.
