### ISSUE TITLE
Violation - Google Chrome notice

### ISSUE THREAD

**Issue by Eldenroot** [martec/Rin-Editor#34]
Is that something what can be fixed by you?
![image](https://user-images.githubusercontent.com/778890/53597401-606ce200-3ba2-11e9-9d0a-6a933addc320.png)

I gets this console notice for CKeditor, thank you!

**Comment by martec** [comment]
please give me steps to reproduce the issue in my test forum below. I tried reproduce issue using chrome 74.0.3720.5 but i don't have sucess. 

https://sites.minnasuki.com/1820

popup user and password

user: test
pass: test123

user and password in test forum

user: testuser
pass: test123

**Comment by Eldenroot** [comment]
ok, I am closing this... it is a part of ckeditor core. maybe updating in future to the newer CKeditor would fix that. Thank you for your input martec!

**Comment by martec** [comment]
if you can give me steps to reproduce in my test site is better. this maybe happened because of plugin of ckeditor and doesn't by core.

**Comment by Eldenroot** [comment]
It happens sometimes, same on your site. It is only a recommendation from Google, not an error. I use latest Google Chrome 64bit stable.
