### ISSUE TITLE
jQuery issue?

### ISSUE THREAD

**Issue by Eldenroot** [martec/Rin-Editor#35]
MyBB 1.8.20, jQuery 3.0.0

https://community.mybb.com/thread-222146-post-1325166.html#pid1325166

**Comment by martec** [comment]
please before report something like, try using clean install of mybb.
i can't reproduce in my test site

https://sites.minnasuki.com/1820

popup user and password

user: test
pass: test123

user and password in test forum

user: testuser
pass: test123
