### ISSUE TITLE
Imgur enhancements

### ISSUE THREAD

**Issue by Eldenroot** [martec/Rin-Editor#36]
Hi martec! Your latest version 0.9.6 is working fine so far, thank you very much!

I think that a lot of users love Imgur integration in your editor. I have few ideas to consider:

- add a support for Ctrl+V (clipboard) keyboard shortcut for pasting images into imgur
- add a support for uploading more than just one image to imgur at once
- drag and drop support?

Just my ideas, free feel to close my ticket :)

Thank you buddy!

**Comment by martec** [comment]
Hi...

- add a support for Ctrl+V (clipboard) keyboard shortcut for pasting images into imgur
you can paste in select image popup dialogue.

- add a support for uploading more than just one image to imgur at once
you only need select more than one image in select image popup dialogue.

- drag and drop support?
you can use plugin like this https://community.mybb.com/mods.php?action=view&pid=386
