### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Eldenroot** [martec/Rin-Editor#37]
![image](https://user-images.githubusercontent.com/778890/62010142-201c8a80-b167-11e9-9315-3bf6bb125e48.png)

Quick reply -> text area -> there is "*" in cursor type

**Comment by martec** [comment]
this is intentional 

https://github.com/ckeditor/ckeditor-dev/blob/ea179097854b8855168e22a9fe6b59c1a034e4f7/plugins/wysiwygarea/plugin.js#L617
