### ISSUE TITLE
Not possible to save b_ skin /1.0.4/

### ISSUE THREAD

**Issue by Eldenroot** [martec/Rin-Editor#41]
I can select b_ skin in my theme, but when I save it it returnd automatically back to the version without the "b_"

![image](https://user-images.githubusercontent.com/778890/102017142-5e6b1780-3d65-11eb-8a8d-8be86aacfef5.png)

**Comment by martec** [comment]
you tried with default theme or modified theme?

**Comment by Eldenroot** [comment]
1) Default mybb theme

I use Fastyle form @shade for editing themes/templates... anyway it happens for all skins with names "B_" inside... is possible to use different way of naming?

**Comment by martec** [comment]
Please give me 1, 2 and 3 result first. I can't help if you not tried to me help understand the root of the problem.

**Comment by Eldenroot** [comment]
1) default 1.8.24 mybb theme
2) same, not working
3) I can make anything else without any issue

**Comment by martec** [comment]
check this post
https://community.mybb.com/thread-159288-post-1358659.html#pid1358659
and this
https://community.mybb.com/thread-159288-post-1358668.html#pid1358668

this is known issue... and not related with my plugin. 
and not possible made any change in theme properties page...
Change "b_" to another thing don't will fix for you. You need ask support to shade, or desactive Fastyle plugin, change to  "b_" skin and reactive Fastyle plugin again.. 

Ticket Closed.

**Comment by Eldenroot** [comment]
I am sorry, didnt know that...

**Comment by Eldenroot** [comment]
Works fine, thank you!

One more thing, how to change the color of the grey bar under the editor? It is a part of editor, maybe is possible to change it via css? Thx

![image](https://user-images.githubusercontent.com/778890/102252461-6615f200-3f06-11eb-84c9-15425910a245.png)

**Comment by martec** [comment]
you need edit css of theme installed.... or install theme that all black like https://ckeditor.com/cke4/addon/prestige
