### ISSUE TITLE
Make wider the smiley box

### ISSUE THREAD

**Issue by Eldenroot** [martec/Rin-Editor#42]
Would be nice to add more columns for smiley popup window box, it looks bad when you use a lot of smileys. It is too narrow and you have to scroll down. I know that there is a config file but would be better to make ti as a default value, lets say to increase by 4?

**Comment by Eldenroot** [comment]
![image](https://user-images.githubusercontent.com/778890/102252310-39fa7100-3f06-11eb-8457-e00cd67526f7.png)

**Comment by martec** [comment]
sorry, normally i don't improve the customization part .... For me, each one should customize according to their needs.
