### ISSUE TITLE
Chnage color in "OK" button from blue to white?

### ISSUE THREAD

**Issue by Eldenroot** [martec/Rin-Editor#43]
It is quite not visible 
![image](https://user-images.githubusercontent.com/778890/102269283-b435f000-3f1c-11eb-85c9-697db41406c9.png)

Any CSS trick?

**Comment by martec** [comment]
sorry, but i don't support customization. and if you are using the default skin of the rin editor, some css is in conflict with your mybb theme ... check the image below:
![Capturar](https://user-images.githubusercontent.com/1976338/102301701-19e2a600-3f36-11eb-8947-85cd3e3e3bbb.PNG)

**Comment by Eldenroot** [comment]
OK, solved, thank you! I had to change the css for links.
