### ISSUE TITLE
Better icons for code/php

### ISSUE THREAD

**Issue by Eldenroot** [martec/Rin-Editor#45]
![image](https://user-images.githubusercontent.com/778890/103245284-f5d48b00-495f-11eb-82db-d0a83588e84f.png)

Is possible to add better icons for moonalisa skin for these 2 buttons to use same style? Also video icon is different.

Just a question and a minor thing :) thx!

**Comment by martec** [comment]
I use these icons due to moonocolor theme https://ckeditor.com/cke4/addon/moonocolor, this theme for now is the standard of Rin Editor. In the future I will change the default of this editor to Moono-Lisa, when that happens the icons will also change together.

**Comment by martec** [comment]
done in 1.1.3. closed.
