### ISSUE TITLE
Different style for code/php and quote blocks

### ISSUE THREAD

**Issue by Eldenroot** [martec/Rin-Editor#46]
Is possible to make the style for all PHP/CODE and QUOTE same in editor?

PHP and CODE block look different, I prefer this style. Quote block looks different in editor, is possible to change it to php/code style? Also is possible to use same popup window for quote like php/code has (for purpose when we use quote button in editor itself in a post).

![image](https://user-images.githubusercontent.com/778890/103245583-ea359400-4960-11eb-9737-315200fd3e5b.png)

**Comment by martec** [comment]
I don't provide support for styles... You need edit by yourself the contents.css https://github.com/martec/Rin-Editor/blob/master/jscripts/rin/editor/contents.css and contents_black.css https://github.com/martec/Rin-Editor/blob/master/jscripts/rin/editor/contents_black.css .
About Code Snippet plugin and Blockquote plugin, they are for different purposes. Code Snippet plugin doesn't accept style inside your tag, I mean, you can't put the color tag, align it, etc. So it's not possible.
