### ISSUE TITLE
Cannot see a post content on quick/full edit

### ISSUE THREAD

**Issue by Eldenroot** [martec/Rin-Editor#49]
One of my user reprted me this error:

In one post (other works completely fine) - there is no possibility to edit the post content. When you click on quick edit or full edit - the editor is empty (even when you switch to source mode)... other replies or threads are completely fine.

I get this in my browser console
![image](https://user-images.githubusercontent.com/778890/105195910-61fb7680-5b3b-11eb-8ce1-c33c0f96808c.png)

Also tested on different PCs and different web browsers... really strange. I can give you test account (admin) to test.

I am on discord, or write me on email or MyBB community board (Eldenroot).

Thank you

**Comment by Eldenroot** [comment]
`Marco Polo - Nehral som tu hru, ale mam ju v nejakom pomyselnom zozname moznych hier, a tak by sa mi zisla informacia, ci to je hratelne alebo nie. Ci sa to oplati kupit alebo nie.
Tym, ze HiG vydava mini rozsirenia pre tuto hru, vyzera to, ze ma tato hra celkom dobru hracsku zakladnu.

Avsak, na zaklade najnovsieho vyhlasenia HiG, sa totiz pre racisticke Daniele Tascini-ho od neho distancuje, a tak ukoncuje docasne (alebo uplne, podla vyvoja situacie) vsetky projekty s autorom hry.

Su teda dve moznosti, autor si najde nove vydavatelstvo a bude v hre pokracovat pod inymi kridlami, alebo tato hra skonci uplne.

Ak si j uale chcete kupit, asi by bolo dobre to urobit co najskor, nakolko je mozne, ze bude hra stiahnuta z trhu uplne.

Na cunco.de je aktualne k dispocii mini rozsirenie Karavany
[url]https://cundco.de/mini-erweiterungen/mar...-des-khan/[/url]`

**Comment by Eldenroot** [comment]
Yes, same happens here.... if the user uses different syntax for url, all is broken

http://sites.minnasuki.com/1820/showthread.php?tid=23

**Comment by martec** [comment]
Thanks for bug report!
Fixed in 1.1.11

**Comment by Eldenroot** [comment]
Thx for fast fix and great support!
