### ISSUE TITLE
private.php - console error?

### ISSUE THREAD

**Issue by Eldenroot** [martec/Rin-Editor#51]
I get this error here: /private.php (inbox)

![image](https://user-images.githubusercontent.com/778890/111524636-fa3d6280-875c-11eb-9623-25d43d7b7f97.png)

**Comment by martec** [comment]
Sorry but this doesn't related to my plugin.
Quick References is calling by CKEDITOR where it is not declared or defined. 

Adding an "if" check like the code below I think solves the problem. 
https://github.com/martec/phpbb3-ext-quickedit/blob/master/styles/prosilver/template/quickedit_body.html#L29
