### ISSUE TITLE
small visual problem

### ISSUE THREAD

**Issue by fighellboy** [martec/Rin-Editor#52]
Hi there,
I know that I use custom appearance template and the extension is probably not completely adapted for it. I wanted to ask how to fix the gap above editor. I'm new to creating web and I'm a little lost and I don't know where to edit it, before I added the extension, the text on the right above the editor was next to the editor and I don't know where I can fix it?
I am not very experienced with web design. Maybe this is not quite a problem with the editor itself but I need advice on how to remove the gap above the editor.

Thanks fo help
Kind regards

![BP8w](https://user-images.githubusercontent.com/64019702/111743848-91540880-888a-11eb-8c68-0c410737f350.png)
![Výstřižek](https://user-images.githubusercontent.com/64019702/111745272-a467d800-888c-11eb-8a9e-745648d22de0.PNG)

**Comment by martec** [comment]
Hello

sorry, but this repository is for the Mybb version. Use the PhpBB topic for related question. https://www.phpbb.com/community/viewtopic.php?f=456&t=2427126
