### ISSUE TITLE
TikTok share URLs aren't parsed correctly

### ISSUE THREAD

**Issue by RealDrDoob** [martec/Rin-Editor#53]
Tested using Rin Editor 1.2.1 on MyBB 1.8.24

Take the following URL: https://www.tiktok.com/@q32reneking/video/6949584890203622657

When posted using the built-in SCEditor, the URL parses fine, but for some reason with rineditor, it stops at the @ symbol, so the URL winds up like this: [https://tiktok.com/](https://tiktok.com/)@q32reneking/video/6949584890203622657

**Comment by martec** [comment]
Hi,

for me working fine using Mybb 1.8.26 with Rin Editor 1.2.1

you can test in link below

https://sites.minnasuki.com/1826

popup user and password

user: test
pass: test123

user and password in test forum

user: testuser
pass: test123

*test forum above using clean install of mybb 1.8.26 with Rin Editor 1.2.1 

This is probably occurring in conflict with some other plugin. It should probably be a mention plugin like MentionMe or DVZ Mention. Then try to disable the aforementioned plugin if you are using it and try it out.
In that case I will not be able to help you, you will have to contact the developer of the respective plugins.
