### ISSUE TITLE
When thread is closed and quick reply is enabled

### ISSUE THREAD

**Issue by Eldenroot** [martec/Rin-Editor#54]
![image](https://user-images.githubusercontent.com/778890/122256270-2d63cf00-cecf-11eb-99f1-5e7111998deb.png)

Can you reproduce?

**Comment by martec** [comment]
no, i can't reproduce issue here...
try make test with clean install in localhost.

you can test too in my test forum
https://community.mybb.com/thread-189422-post-1366109.html#pid1366109

**Comment by Eldenroot** [comment]
Ok, thx
