### ISSUE TITLE
BUG: for sub and sup - not working!

### ISSUE THREAD

**Issue by Eldenroot** [martec/Rin-Editor#56]
![image](https://user-images.githubusercontent.com/778890/150839736-77b6126c-f6fa-421a-9da6-226b90209665.png)

It is rendered correctly only on post edit...

**Comment by Eldenroot** [comment]
@martec - can you reproduce? Thank you

**Comment by Eldenroot** [comment]
@martec - BUMP :(

**Comment by martec** [comment]
the sub and sup are disabled by default, and mybb not offer this tag by default.
if you want use this tags you need create mycode for sub and sup by yourself.

**Comment by Eldenroot** [comment]
Hi, thx for the reply. Can you please tell me the correct syntax for sub and sup mycode? Thx

**Comment by martec** [comment]
probably this work... no tested,
https://community.mybb.com/thread-61540.html

**Comment by Eldenroot** [comment]
thank you!!!
